### PR TITLE
Dodgr

### PR DESCRIPTION
**Pull request by mem48**
A very quick attempt at using `dodgr`

Produced 100 routes in 26 seconds

### CODE REVIEW

**Comment by Robinlovelace** [comment]
@mpadge could you provide a quick review? Any way to optimise this please let us know.

**Comment by mpadge** [comment]
Biggest optimisation step would be calculating paths on contracted graph, and not full graph. Something like this:
``` r
o <- match_pts_to_verts(dodgr_vertices(graph), origins,, connected = TRUE)
d <- match_pts_to_verts(dodgr_vertices(graph), destinations,, connected = TRUE)
graphc <- dodgr_contracted_graph(graph, verts=c(o, d))
paths <- dodgr_paths(graphc, o, d, pairwise = TRUE)
```
One a somewhat smaller network, that sped things up on my machine around 100-fold. The paths returned are then contracted versions, so straight lines between junctions, but it's possible to recover full paths if that's what you want. Let me know.

--

More generally, the paths code hasn't been optimised on the C++ side to nearly the extend of the other code for distances and flows, because there's never been any huge need for that. I could maybe look deeper there if needed ...

**Comment by mpadge** [comment]
I ran your full Leeds example, and went from 51s on my machine to 1.7s for 100 paths. I saw your ballback times on the README, which is an interesting comparison. Then I looked in the C++ code for paths here, and saw that I haven't even parallelised that at all, unlike all other C++ routines. Writing a parallel wrapper around path calculations would enormously speed things up. That said, i haven't done it because storage is non-trivial, unlike for other calculations, but it would be possible.

**Comment by Robinlovelace** [comment]
Thanks for the heads-up Mark, will aim to optimise before merging and get a bit of a table of performances going..

**Review by Robinlovelace — APPROVED** [review]

**Comment by mem48** [comment]
@mpadge while we are on the topic do you have any comments on the path_to_sf functions?

```
path_to_sf <- function(dp, verts) {
    if (length(dp[[1]]) > 0) {
      path <- verts[match(dp[[1]], verts$id), ]
      path <- matrix(c(path$x, path$y), ncol = 2)
      path <- sf::st_linestring(path)
      return(path)
    } else {
      return(NA)
    }
}
paths_to_sf <- function(paths, verts){
  dp.list <- purrr::map(paths, path_to_sf, verts = verts, .progress = TRUE)
  dp.list <- unname(dp.list)
  dp.list
}

```

**Comment by mpadge** [comment]
@mem48 Looks good to me. If you really wanted to make it shorter, you could maybe try `sfheaders` conversion routines? Not necessary though

**Pull request merged**
